# Generated by Django 5.0.4 on 2024-05-13 04:05

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeverify',
            options={'verbose_name': 'code_verify', 'verbose_name_plural': 'code verifies'},
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='codeverify',
            name='code',
            field=models.CharField(max_length=4, validators=[users.validators.check_code_validator]),
        ),
    ]
